#pragma once

#define TILES_IN_A_LINE 24
#define AMOUNT_OF_LINES 10
#define TILESIZE 75

#define TILEMAP_POSITION_X 100
#define TILEMAP_POSITION_Y 300
#define BUTTONS_IN_A_ROW 8
#define AMOUNT_OF_INTERFACE_BUTTONS 24
#define AMOUNT_OF_Building_BUTTONS 8
#define AMOUNT_OF_ECONOMY_BUTTONS 2

#define MAX_PROJECTILES 300
#define PROJECTILE_SIZE 30

#define MAX_ENEMIES 100
#define SPAWN_DISTANCE 100

#define MAX_UNITS 200

#define Building_SIZE 50

#define FIGHTER_ATTACK_DISTANCE 200