#pragma once

#define TILES_IN_A_LINE 24
#define AMOUNT_OF_LINES 10
#define TILESIZE 75

#define TILEMAP_POSITION_X 100
#define TILEMAP_POSITION_Y 300

#define BUTTON_SIZE 50
#define BUTTONS_IN_A_ROW 8
#define AMOUNT_OF_INTERFACE_BUTTONS 24
#define AMOUNT_OF_BUILDING_BUTTONS 8
#define AMOUNT_OF_ECONOMY_BUTTONS 2

#define MAX_PROJECTILES 300
#define PROJECTILE_SIZE 30

#define MAX_ENEMIES 100
#define SPAWN_DISTANCE 100

#define MAX_UNITS 200

#define Building_SIZE 50

#define SPRITE_SIZE 100

#define FIGHTER_ATTACK_DISTANCE 200

#define TECHNOLOGY_TREE_LENGTH 3

#define TECH_POPUPWINDOW_SIZE_X 1000
#define TECH_POPUPWINDOW_SIZE_Y 500

#define BASE_ENEMY_HP 100.0
#define BASE_ENEMY_DAMAGE 10.0
#define BASE_ENEMY_SPEED 10.0
