#pragma once

#define TILES_X 24
#define TILES_Y 10
#define TILESIZE 75

#define TILEMAP_POSITION_X 100
#define TILEMAP_POSITION_Y 300
#define BUTTONS_IN_A_ROW 8
#define AMOUNT_OF_INTERFACE_BUTTONS 24
#define AMOUNT_OF_Building_BUTTONS 8
#define AMOUNT_OF_ECONOMY_BUTTONS 2

#define MAX_PROJECTILES 100
#define PROJECTILE_SIZE 30

#define MAX_ENEMIES 100
#define SPAWN_DISTANCE 100

#define Building_SIZE 50